### ISSUE TITLE
GNU MP: Cannot allocate memory error message

### ISSUE THREAD

**Issue by rozaimirazali** [popgenmethods/smcpp#134] opened 2019-12-05 06:52 UTC
![Screen Shot 2019-12-05 at 9 50 52 AM](https://user-images.githubusercontent.com/37179568/70210875-d101ea00-1744-11ea-946b-eed6370477c2.png)

I am getting this error when trying to run **smc++ estimate**. 

My command is:

`smc++ estimate --cores 32 -o ../output/estimate/ --base F4.15 1.25e-8 ../output/vcf2smc/chr15.F4.smc.gz`

The population that I am studying has a high rate of recent inbreeding. The number of samples in this population is around ~1300 samples

This looks similar to https://github.com/popgenmethods/smcpp/issues/113#issue-418973521 but when I tried to use **-c** instead of masking, I still encounter the same issue

**Comment by terhorst** [comment] 2019-12-06 01:11
Thanks for reporting. This is a duplicate of #38, please see that issue for more information.

**Closed by terhorst** 2019-12-06 01:11 UTC
