### ISSUE TITLE
stalling at: DEBUG1 Computing below_coeffs

### ISSUE THREAD

**Issue by nsmackler** [popgenmethods/smcpp#1] opened 2017-01-10 19:13 UTC
Hi,

Thanks for making this program. I was so excited to use it that I just went all in and tried it on my 218-sample VCF file (starting with chr19, so something relatively small). I was able to successfully generate the smc file, but then the program was stalling in the "estimate" step. When I put in two flags for debugging (-v --verbose), I was able to figure out where it was stalling. The step is:
4279 smcpp._smcpp:src/matrix_cache.cpp:75 DEBUG1 Computing below_coeffs

This happened when I ran it with my own data as well as with your example vcf here:
https://github.com/popgenmethods/smcpp/tree/master/example

Could this be due to missing dependencies? Is this an error that you've noticed before?

On a related note: how long should take to run the "estimate" function in 218 samples? I imagine not that long, but wanted to double-check. Is there a way to mutli-thread to speed things up? 

Thanks,
Noah

**Comment by terhorst** [comment] 2017-01-10 19:31
Hi Noah,

Thanks for trying out our software. I'm not immediately sure what the cause of this is, but it sounds potentially like a threading issue. Can you tell me more about what platform you are on? You definitely should not encounter any issues with our example vcf; the build system verifies (on both Mac and Linux) that it runs correctly before putting out a release. Thanks,

Jonathan

**Comment by nsmackler** [comment] 2017-01-10 19:35
Hi Jonathan,

I'm running this on my HPC cluster here at Duke. It's a linux OS with a SLURM based scheduler. 

I need to define the tell my scheduler the number of threads per job, but I didn't know that it multithreaded as a default. Is there a default number of threads that it looks for? If so, what is it? I can try and see if that fixes it.

Thanks for the quick response,
Noah

**Comment by terhorst** [comment] 2017-01-10 19:42
The number of threads is controlled by the OMP_NUM_THREADS environment variable. If you are only running with one thread then I could see that potentially taking a little while for n=218 -- what this step is doing is recursively computing entries of a nxn matrix in exact (rational) arithmetic. For n in the hundreds I've seen it take a couple of minutes on our machine (24-core with 256gb RAM). On the plus side, the result of this computation is cached and stored between runs, so it only needs to happen once for a given sample size. 

However, for the example VCF this step should be almost instantaneous, so I suspect something else might be going on. Do you know what the process's CPU usage is when it's stuck on this step?

**Comment by nsmackler** [comment] 2017-01-10 19:49
Jackpot. That variable wasn't set, so I just set it:
export OMP_NUM_THREADS=1

Then the example made it through the below_coefs step, but stalled here:
4003 smcpp.analysis INFO Running E-step

I'm going to guess there are some other environmental variables that need to be set that I don't have set up by default. Where can I find all of the variables that are required? 

Thanks,
Noah

**Comment by terhorst** [comment] 2017-01-10 19:59
Actually this is the only salient environment variable, everything else is controlled by command-line options. If you pass '-vv' to estimate what does it say about E-step? Again, it should be instant for the example data.

**Comment by nsmackler** [comment] 2017-01-10 20:02
Ok thanks. It freezes here:

4249 smcpp.analysis DEBUG knots in coalescent scaling:
[ 0.005       0.00910282  0.01657227  0.03017088  0.05492803  0.1         0.18205642  0.3314454   0.60341763  1.09856054
  2.        ]
4249 smcpp.analysis DEBUG Long term avg. effective population size: 0.645860
4251 smcpp.analysis DEBUG Creating inference manager...
4254 smcpp._smcpp:src/inference_manager.cpp:51 DEBUG1 creating HMM
4259 smcpp.optimizer INFO Starting EM algorithm...
4259 smcpp.optimizer INFO EM iteration 1 of 1...
4259 smcpp.analysis INFO Running E-step

**Comment by nsmackler** [comment] 2017-01-11 13:11
A quick update. The processes CPU usage is pretty much nothing when it freezes at this step, so it's clearly stalling. I'm not getting any additional information past:
3921 smcpp.analysis INFO Running E-step
when I use the "-vv" flag. 

Any ideas?

**Comment by terhorst** [comment] 2017-01-11 16:20
Yep, seems like a threading issue. It's difficult for me to debug this
without having access to your system. My best guess is that there's some
sort of conflict between the threading library packaged with smc++ and
whatever is on your cluster. I think the solution is to try and build
locally. I'm working on turning smc++ into a conda package which will make
it easier to do so. I should have this done by the end of the day. Once
it's done I'll contact you. Thanks for your patience!

On Wed, Jan 11, 2017, 5:11 AM Noah Snyder-Mackler <notifications@github.com>
wrote:

A quick update. The processes CPU usage is pretty much nothing when it
freezes at this step, so it's clearly stalling. I'm not getting any
additional information past:
3921 smcpp.analysis INFO Running E-step
when I use the "-vv" flag.

Any ideas?

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/popgenmethods/smcpp/issues/1#issuecomment-271864742>,
or mute the thread

**Comment by nsmackler** [comment] 2017-01-12 00:47
Thanks. Please do keep me posted. The job scheduler is SLURM, so that does all of the threading. I haven't had issues with threading in other programs (alignment, SNP calling, pretty much anything), so it would be good to figure this out. As I said, we'd like to run this on all 218 animals across each chromosome. It would be great to do it on the cluster rather than a desktop.

Thanks again
Noah

**Comment by terhorst** [comment] 2017-01-12 06:00
Hi again,

Could you please try installing the [conda package](https://anaconda.org/terhorst/smcpp)? For this to work you will first need to install [miniconda](http://conda.pydata.org/miniconda.html), and then run
    
    $ conda install -c terhorst -c conda-forge -c bioconda smcpp

(Sorry, I know this is slightly more work than downloading the binary. My hypothesis is that there's something weird about the way the binary packaging mechanism handles OpenMP.)

**Comment by nsmackler** [comment] 2017-01-12 13:02
I tried installing it, but it looks like it froze here:
conda install -c terhorst -c conda-forge -c bioconda smcpp
Fetching package metadata ...

**Comment by terhorst** [comment] 2017-01-12 13:04
Maybe try ``--verbose``? That should definitely not be freezing under any
circumstance.

**Comment by nsmackler** [comment] 2017-01-12 14:00
Looks like it's getting stuck here:
DEBUG conda.fetch:fetch_repodata(87): Opening repodata cache for https://repo.continuum.io/pkgs/free/noarch at /home/nms15/.conda/envs/.pkgs/cache/524e4676.json
DEBUG requests.packages.urllib3.util.retry:from_int(191): Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
DEBUG conda.fetch:fetch_repodata(87): Opening repodata cache for https://repo.continuum.io/pkgs/pro/linux-64 at /home/nms15/.conda/envs/.pkgs/cache/1af9ae67.json
DEBUG conda.fetch:fetch_repodata(87): Opening repodata cache for https://repo.continuum.io/pkgs/pro/noarch at /home/nms15/.conda/envs/.pkgs/cache/f1a0ac49.json

Could certainly be on my end.

**Comment by terhorst** [comment] 2017-01-12 22:27
Is it possible that the node you're working on is behind a firewall, or in some way prevents HTTP requests to the outside world? I've seen this on some other clusters before.

**Comment by nsmackler** [comment] 2017-01-13 04:24
Ah - yes, that's right. It is behind a firewall and prevents https, but not http requests (looks like it is https:). I'll see if my IT team can find a way around this.

-Noah

**Comment by terhorst** [comment] 2017-01-15 05:23
It turns out there is a way to pre-package all of the required Conda stuff into a single executable. This should be more reliable than the pyinstaller-based method I was using before. Could you please give the [new installation procedure](https://github.com/popgenmethods/smcpp#installation-instructions) a whirl and let me know what happens? Thanks.

**Comment by nsmackler** [comment] 2017-01-15 12:59
Hi Jonathan,

Thanks for putting the new installation procedure together. I just gave it a whirl and ran into this error when I tried to run smc++:
Traceback (most recent call last):
  File "/data/tunglab/nsm/programs/smcpp/bin/smc++", line 4, in <module>
    import re
  File "/data/tunglab/nsm/programs/smcpp/lib/python3.5/re.py", line 335, in <module>
    import copyreg
  File "/data/tunglab/nsm/programs/chromosomer/copyreg/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.

It was a similar error to what I was getting before, but I can't seem to get around it by loading different version of python this time...

**Comment by terhorst** [comment] 2017-01-15 20:03
Try typing ``source /data/tunglab/nsm/programs/smcpp/bin/activate`` before running ``/data/tunglab/nsm/programs/smcpp/bin/smc++``.

**Comment by nsmackler** [comment] 2017-01-16 12:30
Ah, I see, it's a virtual environment. Unfortunately there is no "activate" file. Is it supposed to be part of the installation?

**Comment by terhorst** [comment] 2017-01-16 16:15
No, that was an assumption on my part. Maybe try unsetting your PYTHONPATH first?

**Comment by nsmackler** [comment] 2017-01-16 16:31
That did it, but now we're back to where we were: It's freezing at the EM step when I use the example data.  Here is the full output:

smc++ estimate -vv -o example_out example.smc.gz 
1144 smcpp.commands.estimate DEBUG ['/data/tunglab/nsm/programs/smcpp/bin/smc++', 'estimate', '-vv', '-o', 'example_out', 'example.smc.gz']
1145 smcpp.commands.estimate DEBUG Namespace(M=32, N0=10000.0, Nmin=0.01, algorithm='L-BFGS-B', block_size=3, command='estimate', data=['example.smc.gz'], em_iterations=10, factr=1e-09, knots='10', length_cutoff=10000, no_filter=False, no_initialize=False, nonseg_cutoff=None, offset=0.0, outdir='example_out', pieces='32*1', prior_model=None, regularization_penalty=1.0, rho=None, spline='cubic', t1=100, tK=40000.0, theta=None, thinning=None, tolerance=0.0001, verbose=2)
1147 smcpp.analysis INFO Loading data...
stack trace:
1362 smcpp.analysis DEBUG Contig(pid=('pop',), fn='example.smc.gz', n=array([4]), a=array([2]))
1366 smcpp.analysis INFO 1 population
1368 smcpp.analysis DEBUG Average heterozygosity (derived / total bases) by data set (* = dropped)
1368 smcpp.analysis DEBUG example.smc.gz:
1368 smcpp.analysis DEBUG               0         100000         100001 0.000619994
1369 smcpp.analysis INFO 0.00 Gb of data
1370 smcpp.analysis INFO theta: 0.000480
1371 smcpp.analysis INFO rho: 0.000480
1371 smcpp.analysis DEBUG Nmax calculated to be 116.279
1375 smcpp.analysis DEBUG time points in coalescent scaling:
[ 0.005       0.00102954  0.00124153  0.00149718  0.00180546  0.00217722  0.00262553  0.00316614  0.00381808  0.00460426
  0.00555231  0.00669558  0.00807426  0.00973681  0.01174171  0.01415943  0.01707497  0.02059086  0.02483069  0.02994354
  0.03610917  0.04354436  0.05251051  0.06332288  0.0763616   0.0920851   0.11104621  0.13391158  0.16148512  0.19473628
  0.23483415  0.28318851  0.34149945]
1376 smcpp.analysis DEBUG knots in coalescent scaling:
[ 0.005       0.00910282  0.01657227  0.03017088  0.05492803  0.1         0.18205642  0.3314454   0.60341763  1.09856054
  2.        ]
1376 smcpp.analysis DEBUG Long term avg. effective population size: 0.645860
1377 smcpp.analysis DEBUG Creating inference manager...
1378 smcpp._smcpp:src/inference_manager.cpp:51 DEBUG1 creating HMM
1380 smcpp.optimizer INFO Starting EM algorithm...
1380 smcpp.optimizer INFO EM iteration 1 of 1...
1380 smcpp.analysis INFO Running E-step

And it just freezes there. I set OMP_NUM_THREADS ==1 and have also tried this while multi-threading across 32 cores on my cluster.

**Comment by terhorst** [comment] 2017-01-17 17:41
I'm sort of out of ideas here, unfortunately. You could try downloading the latest version (v1.4.1), which disables Intel MKL. There's a remote chance that that has something to do with it. Otherwise, I would recommend compiling locally using ``pip`` and/or consulting with your sysadmin to see if they have any ideas. (If you or anyone you know is proficient in ``gdb``, a stack trace of each thread when the program hangs would be useful.) As far as I can tell you are the only user experiencing this problem, but I will leave this issue open for now in case anybody else is getting the same error.

**Comment by ColyFu** [comment] 2017-02-09 07:45
hi there,
I have encountered the same problem(the program stalling at: DEBUG1 Computing below_coeffs.).
Has anyone solved this problem?

**Comment by terhorst** [comment] 2017-02-09 12:04
Can you give me some details on your platform? Also, have you tried
building the software yourself, as described in the README? Thanks.

**Comment by ColyFu** [comment] 2017-02-13 09:13
Hi, Jonathan，
Thanks!
We have solved this problem by installing the newest version(v1.6.1) by Anaconda.
The problem occurred in our own build version(v1.3.8), and the platform,

- CentOS release 6.6 64bit, kernel 2.6.32-504.el6.x86_64,
- memory 96 G, 
- CPU：Intel(R) Xeon(R) CPU E7- 4850  @ 2.00GHz.

Now I encountered a new problem,

- libgomp: Thread creation failed: Resource temporarily unavailable

sorry, but I don't know how to limit the threads.
Thank you!

**Comment by terhorst** [comment] 2017-02-13 12:52
You can control the number of threads by setting the OMP_NUM_THREADS environment variable.

**Comment by ColyFu** [comment] 2017-02-15 06:30
It worked like a charm! Thanks!

**Comment by terhorst** [comment] 2017-02-24 18:31
Closing this as it seems to be fixed...

**Closed by terhorst** 2017-02-24 18:31 UTC
