### ISSUE TITLE
Unable to recreate Supp Fig 2-4 in the SMC++ paper

### ISSUE THREAD

**Issue by rozaimirazali** [popgenmethods/smcpp#172] opened 2020-10-29 07:10 UTC
Hello. I failed to re-create the same plot in the Supp Fig 2-4 of the Suppl Material paper.

FYI, i am using the latest smc++ version 1.15.2

For example, this is what was published in the paper:

![Screen Shot 2020-10-29 at 10 05 51 AM](https://user-images.githubusercontent.com/37179568/97536564-6433b600-19ce-11eb-856d-b3065d6dc12b.png)

but what I am getting is:

![Screen Shot 2020-10-29 at 10 06 06 AM](https://user-images.githubusercontent.com/37179568/97536601-76155900-19ce-11eb-901a-6684c83308cb.png)

As you can see in the Supp Mat figure, the CHB and GIH are closer as they approach 1000 years.

Could you please share the exact command that you ran for vcf2smc and estimate? Thanks

**Comment by terhorst** [comment] 2020-10-29 14:28
To generate the data files, I used the options `vcf2smc --mask centromeres.bed.gz <pop>:<samples>`, where `centromeres.bed.gz` are the locations of the centromeres in whatever coordinate system you're using, and pop/samples vary from population to population. The sample IDs used for each of the populations in question are attached. Please note that these sample IDs refer to a merged dataset containing samples from both the Complete Genomics and 1kg datasets. For the distinguished lineages we used the ones at the top of each file ending in `200-37-ASM`, which come from the CG dataset.

To perform estimation I used `estimate --timepoints 33 100000 -c 50000 -rp .1 --knots 60 1.25e-8`. (This is not the exact command, because the options for `estimate` have evolved over the years, but it should be equivalent.)

Please note that the code has changed substantially (for the better I hope) since publication. If trying to exactly reproduce the plots from the paper, you'll want to revert back to v0.0.1. If you just care about estimation, you should upgrade to the most recent version.

[files.zip](https://github.com/popgenmethods/smcpp/files/5458984/files.zip)

**Comment by rozaimirazali** [comment] 2020-11-02 07:03
> To generate the data files, I used the options `vcf2smc --mask centromeres.bed.gz <pop>:<samples>`, where `centromeres.bed.gz` are the locations of the centromeres in whatever coordinate system you're using, and pop/samples vary from population to population. The sample IDs used for each of the populations in question are attached. Please note that these sample IDs refer to a merged dataset containing samples from both the Complete Genomics and 1kg datasets. For the distinguished lineages we used the ones at the top of each file ending in `200-37-ASM`, which come from the CG dataset.
> 
> To perform estimation I used `estimate --timepoints 33 100000 -c 50000 -rp .1 --knots 60 1.25e-8`. (This is not the exact command, because the options for `estimate` have evolved over the years, but it should be equivalent.)
> 
> Please note that the code has changed substantially (for the better I hope) since publication. If trying to exactly reproduce the plots from the paper, you'll want to revert back to v0.0.1. If you just care about estimation, you should upgrade to the most recent version.
> 
> [files.zip](https://github.com/popgenmethods/smcpp/files/5458984/files.zip)

Hi. Thanks for the reply! I really appreciate it. 

Based on your opinion, is it possible that the estimated effect size can change with the latest version? For example, in the paper, at 1000 years, GIH has a higher effective size compared to CHB but in the plot I generated using the latest version, GIH never surpassed CHB.

I just want to sure that I am running the tool correctly. The way I ran estimate is :

1. Ran estimate per population to create per population json file

![Screen Shot 2020-11-02 at 10 01 21 AM](https://user-images.githubusercontent.com/37179568/97839082-85f4ac00-1cf2-11eb-818c-ffc091fa00b7.png)

2. Plot the 3 json file

![Screen Shot 2020-11-02 at 10 03 03 AM](https://user-images.githubusercontent.com/37179568/97839140-9f95f380-1cf2-11eb-8ea0-e796b883a2f2.png)

**Comment by terhorst** [comment] 2020-11-02 14:21
The results should be fairly consistent across versions, but modifications to the algorithm, or differences in the datasets used, could result in slight variations, sure. It's important to keep in mind that these estimates are random and subject to statistical noise. This is especially true in the recent past.

**Closed** 2020-12-24 07:10 UTC
